apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
        - name: prometheus
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
