apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asyncforge
# Changed from bases to resources to fix the deprecation warning
resources:
  - ../../base
  - ../../rabbitmq
  - ../../migrate
  - ../../web
  - ../../dispatcher
  - ../../worker
  - ../../ingress